GROUP_REPOS = [
    [
        "group a",
        "ZeroDownTime",
        ["https://github.com/ZeroDownTime-ITU/minitwit_project"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group c",
        "group c",
        ["https://github.com/jskoven/Devops2026_jklo_jakst_aing_asjo_mbln"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group d",
        "Dense Dino Nuggets",
        ["https://github.com/Slug-Boi-ITU-Repositories/Dense-Dino-Nuggets"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "DevOpps",
        ["https://git.marfavi.com/DevOpps/itu-minitwit-migration"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group h",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group i",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group j",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group k",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group l",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group m",
        "Holy C Enjoyers",
        ["https://github.com/MudiLoodi/minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group o",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group p",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group q",
        "<DevTroopers",
        ["https://github.com/leosakharoff/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
]
